### ISSUE TITLE
Line 418, drop if command == None

### ISSUE THREAD

**Issue by Leryan** [shinken-monitoring/mod-booster-nrpe#19]
Hi,

Can we drop `command is None` and only replace it by an empty string?

``` python
if command is None or host is None:
```

It is not required to run a command with NRPE, so it shouldn't be required here.

If you agree with that, I can work on it, test it and make you a pull request.

**Comment by Leryan** [comment]
Someone shown me that `check_nrpe` sends `_NRPE_CHECK` if no command is specified. So the patch is simple: just force `command = '_NRPE_CHECK'` if `command is None`, and that's all.

**Comment by gst** [comment]
Just for my information,
what's the meaning of `_NRPE_CHECK` if not command is specified.. ? thx.

**Comment by Leryan** [comment]
It's like a ping for NRPE. The remote NRPE server will send the Nrpe version. It's a string like "NRPE v2.15", iirc.
